apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: image
global:
  registry:  ${LOCAL_REGISTRY}:5000

charts:
- name: keycloak-operator
  override:
    image.repository: $(registry)/keycloak/keycloak-operator
    image.tag: "17.0.0"

- name: keycloak-resources
  override:
